### ISSUE TITLE
Changes needes in motus R package for Node Data Mgmt

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#528]
Moving this email to github

1.	a few existing tables need new fields added. Steffi, if you could add those 3 fields in the sandbox and beta2 branch today or tomorrow, that’d be great. I can manually add them to my local sqlite file as a backup for now.

batches;
new field called source (already in the R views and sample data) as TEXT

runs;
new field called nodeNum (already in the R views and sample data) as TEXT

gps:
new field called quality (already in the R views and sample data) as INTEGER

Catherine, could you compare the DET tables, the views and the R schema to see if we are missing anything else? Not all fields in the DET tables are relevant. A few will likely get removed entirely as they won’t be used (e.g. nodeNum in taghits has been replaced by nodeNum in runs).

2.	We also need a new table called nodeData, but this one is less pressing. I suggest we wait until Catherine has had a chance to look at the new views I created. The projectID and motusDeviceID fields can be stripped out by the API. Catherine, once the views are ready, can you signal Paul to set up 2 new API entry points for those? Steffi, you can then add this new table in R and include it in the tagme loops.

[vwR_Node_data_for_tag_project] 
      id, batchID, ts, nodeNum, ant, sig, battery, temperature, projectID
[vwR_Node_data_for_receiver]
      id, batchID, ts, nodeNum, ant, sig, battery, temperature, motusDeviceID

This is the underlying table and field definitions

CREATE TABLE [dbo].[det_node_data](
      [id] [bigint] PRIMARY KEY IDENTITY(1,1) NOT NULL,
      [batchID] [bigint] NOT NULL,
      [ts] [float] NOT NULL,
      [nodeNum] [varchar](20) NOT NULL,
      [ant] [smallint] NOT NULL,
      [sig] [float] NULL,
      [battery] [float] NULL,
      [temperature] [float] NULL)

We’ll have to see if we need to deal with permissions in some other ways by linking to securable, etc.  I’m hoping we can keep things simple.

**Comment by cjardine-bsc** [comment]
#523

**Comment by denislepage** [comment]
Some notes below YES/NO on changes needed in R.

Steffi, nodeNum is a text field, btw.

My preference would be to avoid setting up API entry points that we don’t need for sample node data, and have R bypass those. Steffi can confirm. Alternatively, if needed, Paul can probably handle this in the API only to return an empty response for those (no need for empty sample tables).

On your last question, nodes are independent from antennae. I think what you are seeing is the latter case: a node signal is being picked up by multiple antennae. There are also possibilities that a node will be picked up on multiple receivers, which could get a bit tricky for users to resolve. Node numbers are only locally unique, so resolving a node number that isn’t listed in the receiver metadata will entail a geographic or project component. It may be worth checking with CTT if they would consider making them globally unique.

  1.  Comparison!

det_ambig: Nothing new.
det_ambig_tags: Nothing new
det_batches:
YES New field Source : added (vwR_Batches_activity, vwR_Batches_for_receiver,vwR_Batches_for_receiver_project,vwR_Batches_for_tag_project)

NO (for now) New field batchUID: this tracks batches for CTT file handling (mostly useful across sandbox and live db’s – internal use only).
NO New field is_new: not needed-internal.
YES det_batches_activity: Change ant field to text
det_gps:
YES new field: Quality to be added.
YES New field: GpsID used to paginate download, added?
YES det_pulse_counts: change ant to text
NO det_runs: New field: TagCode Denis, I'm assuming you're just tracking this here, and it's not needed in R?

I am almost positive this is just a remnant to be removed, but we should confirm.

YES New field: nodeNum to be added.
YES Ant needs to be changed to text
Perhaps too late? det_runs_filters:Nothing new. But we did not establish whether we want to change the name of the motus filter column based on the mismatch of the concept of probability.
NO. det_taghits: New field: bitErr probably not needed?



  1.  I made a couple tiny changes to the view (changed id to nodeDatID to minimize R joining confusion).

The other view we'll need is for the node metadata. We don't have any of this data yet, but I've set up the view.

CREATE VIEW vwR_Metadata_for_receivers_nodeDeps
AS
SELECT a.project_id as projectID, e.id as deviceID, b.id as deployID, c.[id] as nodeDeployID
,[nodeNum],c.[latitude],c.[longitude]
,dbo.datetime2ts(c.[dt_start]) AS tsStart,dbo.datetime2ts(c.[dt_end]) AS tsEnd
FROM sensors a
LEFT JOIN sensors_hash_keys e on a.receiverID = e.receiverID
INNER JOIN sensor_deployments b on a.id = b.sensor_id
INNER JOIN sensor_nodes c on b.id = c.deployment_id
INNER JOIN vwProjectsSecurables d on a.project_id = d.project_id AND d.securable = 'receivers_deployments'

Can Steffi or Paul advise whether we need to create empty sample tables for these three views even if we'll have none of this data available for the sample data?

Final thing I noticed when I was looking at these nodes, is that there are multiple antenna's for each node in the det_node_data column. I'd like to clarify if this means there are multiple antenna for each node, or whether it's just the node data being picked up on multiple antennas on the sensor.

**Comment by pmorrill** [comment]
The 'dep' data is returned as part of the 'recv_metadata_for_projects' entrypoint. It is a nested JSON structure. With the addition of this new set, we will be returning 3 sets of 'dep' data within the receiver metadata response:

a) recvDeps
b) antDeps
c) nodeDeps

When a project contains no 'SENSORSTATION' receivers, this third structure will be empty, I assume (will test!)

I can probably just return an empty structure when the 'sample' data is being called for, or I could just leave this element out entirely. I will take the former course for now, but Steffi can advise if she needs something different.

**Comment by steffilazerte** [comment]
Right now when I access the sandbox API via the "custom/recv_metadata_for_projects" entrypoint, I only receive "recvDeps", "projs", "antDeps" (no nodeDeps).

I am using Project 4 which does have SENSORSTATION receivers listed. Is this because the nodeDeps hasn't been implemented yet? Am I jumping the gun?

Empty structure should be fine for all projects that have no SENSORSTATIONS (as long as it is named, it can be empty, it can also be missing, but it's easier to ensure that everything is working as it should if it's present but empty.)

The only drawback is that the more special options we have that are not in a sample data, the less robust my unit tests will be.

**Comment by denislepage** [comment]
Some ctt detections have a node value, but we don't have node metadata yet. We may want to create some in sandbox for testing. We'll have to think about unit testing options for ctt data.

**Comment by pmorrill** [comment]
The 'nodeDeps' structure was just added to sandbox (master branch) yesterday. I Jeremy builds this morning, you should be able to see nodeDeps data as part of the recv_metadata response package.

**Comment by pmorrill** [comment]
BTW: there is no special handling for sample data yet. It will likely fail if you request recv metadata for sample project. I will try to get that in place today.

**Comment by denislepage** [comment]
Currently, node data is irrelevant to Lotek tags. I am not sure if a adding CTT tags to the sample data would be useful.

Until then, to keep the sample data compatible with the main data, we could have an API entry point that returns an empty JSON object for things not in the sample data. That would prevent having to create exceptions in the R code to avoid pulling certain data tables when dealing with motus.sample.

**Comment by pmorrill** [comment]
Just to update the status: the nodeDeps sub-structure should now we returned when querying for receiver metadata. If you query using the sample credentials, the nodeDeps structure will be empty.

These changes are in master (sandbox) and beta9 branches.

**Comment by steffilazerte** [comment]
I just realized that we've been talking about two different types of node data (metadata vs. data), so I think I need some clarification! I'm going to summarize the discussion regarding these two features to make sure I've understood what's going on :)

[Above](https://github.com/MotusDev/Motus-TO-DO/issues/528#issue-477064836) @denislepage mentioned that the R package will need a new table: `nodeData` with fields  `id`, `batchID`, `ts`, `nodeNum`, `ant`, `sig`, `battery`, and `temperature`. I've created this table in the R package, but as far as I know, there isn't an API point for this data.

[Next](https://github.com/MotusDev/Motus-TO-DO/issues/528#issuecomment-525920775) @cjardine-bsc mentioned that we will also need access to node metadata, which @pmorrill set up to be accessed through the `custom/recv_metadata_for_projects` api entry point. This returns the following fields: `deployID`, `nodeDeployID`, `latitude`, `longitude`, `tsStart`, `tsEnd`. 

Can I assume:
1. Node Data: There isn't an API point yet (i.e. I put this on hold for now)
2. Node Metadata: This should be put in a new table `nodeDeps` with the fields names as they are returned by the API. Should `nodeDeployID` be the primary key? Or both `deployID` and `nodeDeployID`? Or just `deployID`?

**Comment by pmorrill** [comment]
Re #1 - as yet there is no nodeData entry point. But I see that in sandbox we have views (vwR_Node_data_for_receiver and vwR_Node_data_for_tag_project).  Catherine, are these ready to go ahead? And, is this for beta9?

**Comment by cjardine-bsc** [comment]
Yes, you can add those views to the api. They are empty at the moment, but will be populated as more CTT receivers come online.

**Comment by pmorrill** [comment]
And, what are the ordering fields? I see id, nodeNum, and ts. Is the order clause this:

order by nodeNum,ts

or

order by id,ts

**Comment by denislepage** [comment]
The latter: id, ts

**Comment by denislepage** [comment]
Actually, "id" only should be sufficient, no need for ts.

**Comment by pmorrill** [comment]
I am not clear on what the client will request. As part of the tagme() workflow, will the node-data query be made for a specific batchID? 

If so, the api can use something like this:

select top(1000) * from vwR_Node_data_for_tag_project where batchID = ? and id > ?
order by id

**Comment by denislepage** [comment]
Yes, that query looks good.

I just also realized that some of these new API entry points will require table indexes. I have added one for node_data just now. I may have overlooked a few more.

**Comment by pmorrill** [comment]
I am also wondering about the underlying views. vwR_Node_data_for_tag_project includes a field 'projectID' (pulled from 'det_batches_projects').

Is this the tagProjectID of the detection?

**Comment by pmorrill** [comment]
There are 2 new entrypoints in the SG data servlet that supports the R-client. Both return detection records assoicated with CTT nodes (of which we have none in our database, at the moment).

1. /nodes_for_tag_project => this is a paginated call that requires a valid tag project ID and batch ID.

2. /nodes_for_receiver => a paginated call that requires a valid batch ID

Both of these calls are paginated via the 'id' field (node detection id). 

I would like to add complete documentation for these to https://github.com/MotusWTS/motus/blob/staging/inst/doc/upstream_api.md, but may wait until Steffi has considered how to integrate them into the client.

**Comment by steffilazerte** [comment]
A couple of questions:

- @denislepage since there are two entry points which differ depending on the type of download, I was thinking of integrating the node download as part of the `motusUpdateTagDB()` and `motusUpdateReceiver()` functions. For example,  the `motusUpdateTagDB()` function first grabs `batchID`s then:
    - gets `runs` for batch
    - get `hits` for batch
    - get `gps` for batch
    - and now gets `nodeData` for batch. 

  Does that sound reasonable? (I don't know what `nodeData` is, so I thought I'd best ask!). In contrast, the `activity()` function is called after all the batches are downloaded, because it applies only to batches (either tag databases OR receiver databases).

- Would `id` be better as `nodeID` to parallel `batchID`, `gpsID`, etc.?

- @pmorrill when accessing the sandbox API with either API entry point I get: "Error: The feature you tried to access is not implemented." (on both motus.sample and steffilazerte users)
For completeness, this is the full address I'm using: https://sandbox.motus.org/api/sgdata/custom/nodes_for_tag_project

**Comment by denislepage** [comment]
Good points.

Nodes are small portable units that detect tags and relay the information to the base station. They have 3-digit ID’s (e.g. 1f3).

Tags that are originally detected on a node will be identified in the runs table (a run will be specific to a single node in that case, just like they are specific to antennae on the base stations).

Node data, at least for the moment, will only apply to batches that relate to CTT data (source = ‘ctt’ in batches). If you are including the call to node data in the batch loop, you probably only need to do it when the source is ctt. That would likely be my preference.

The node data is only meant to be health data about the nodes themselves, so they have limited value (other than to indicate that they are within range and able to transmit tags if they fly by).

The name NodeID may be a bit confusing to have in the node data table. We already use nodeNum for the 3-digit alpha code. I get the issue, but I don’t have a good solution to offer.

**Comment by pmorrill** [comment]
I am seeing the same 'not available' error on the nodes_for_tag_project call on sandbox. I suspect something did not get fully deployed this morning (the changes went in yesterday, but there was a compile error that would have prevented a successful build). Denis or I will sort this out....

Also: there is no 'sample' data for nodes (yet..??) and so even if this entrypoint is available, you will see an error generating the data when using the sample account.

**Comment by steffilazerte** [comment]
> @denislepage 
The name NodeID may be a bit confusing to have in the node data table. We already use nodeNum for the 3-digit alpha code.

So the idea behind the `id` is because it's numeric, so we can paginate over it? That's why we use `id` rather than `nodeNum`? Fair enough :)

> @denislepage 
Node data, at least for the moment, will only apply to batches that relate to CTT data (source = ‘ctt’ in batches). If you are including the call to node data in the batch loop, you probably only need to do it when the source is ctt. That would likely be my preference.
>
> The node data is only meant to be health data about the nodes themselves, so they have limited value (other than to indicate that they are within range and able to transmit tags if they fly by).

In this case, perhaps the best idea would to have a separate function that is called after the download is complete and which first checks if there are any nodes (source == "ctt") to download data. This would be similar to the `activity()` function which is called automatically by the `tagme()` function, but is also usable directly by the user.

> @pmorrill Also: there is no 'sample' data for nodes (yet..??) and so even if this entrypoint is available, you will see an error generating the data when using the sample account.

Okay good to know! I know the sample account isn't always up to date so I usually check with both but it's always good to know when it's expected to fail :)

**Comment by cjardine-bsc** [comment]
The sample data is all from Lotek currently. We won't have any Node data in there unless we opt to include some CTT data in the sample tables. That won't be for a little while yet (we'll have to get data and permissions to use it as sample first). So we need to ensure that the sample data still returns correctly even without Node data. I can set you up a set of empty sample node tables if that would be helpful.

**Comment by denislepage** [comment]
I don’t know if Jeremy republished sandbox, but I just did again, in any case.

I don’t think we intend to have sample data tables for node_data, so this API call for sample should return an empty JSON, rather than query the database. We can create an empty table if that makes it easier.

**Comment by pmorrill** [comment]
Sounds good. I will return an empty json object for the sample account. Easily done.

**Comment by pmorrill** [comment]
Empty JSON structure now returned when requesting node data via sample account....

**Comment by steffilazerte** [comment]
I'm getting a couple of server errors (sandbox API), possibly because not everything has been deployed:

1. Sample account, project 176: "Failed to generate node data for tag project."
2. Personal account, project 4: "Failed to generate node data for tag project."
2. For receivers, SG-3115BBBK1127, SG-3115BBBK0782, SG-3115BBBK0782, : "You do not have permission to access the data for this project or receiver. Please contact Motus support." (But there's no problem with downloading batches, runs, activity, etc.)

**Comment by pmorrill** [comment]
Sorry: my note implied that the support was deployed. But, it will be tomorrow morning before the sandbox is updated with the changes.

**Comment by steffilazerte** [comment]
Thanks, what about the receivers? Is that just from lack of deployment? Or is that something else?

**Comment by pmorrill** [comment]
I don't recall how we support tagme(recvID) for the sample account... ?? Do we support that?

The only project that we allow for the sample account is 176, so maybe it has to be a receiver registered to that project? I am sort of guessing (working on a different thing at the moment).

Denis did re-deploy sandbox - you could try again (I have not had a chance to test yet).

**Comment by cjardine-bsc** [comment]
Sample data is only supported for project Id. Not for recvID.

**Comment by cjardine-bsc** [comment]
The ID fields in vwR_Node_data_for_receiver and vwR_Node_data_for_tag_project have been changed from "Id" to "nodeDataID" 

So you should expect that field.

**Comment by steffilazerte** [comment]
Sorry for the confusion! To clarify, the receivers were tested with my personal user acount (steffilazerte).

Still problems but slightly different ones? Update:
1. Sample account, project 176: Returns empty object. Should this have empty, but named, list? [different]
2. `steffilazerte` account, project 4: Error "Failed to generate node data for tag project." [same as before]
3. `steffilazerte` account, receivers SG-3115BBBK1127, SG-3115BBBK0782, SG-3115BBBK0782: Error "You do not have permission to access the data for this project or receiver. Please contact Motus support." (But there's no problem with downloading batches, runs, activity, etc.) [Same as before]


@cjardine-bsc   
> The ID fields in vwR_Node_data_for_receiver and vwR_Node_data_for_tag_project have been changed from "Id" to "nodeDataID"

Does that mean (a) I should change the query `id` to `nodeDataID`? or (b) I should update the table to expect a field called `nodeDataID` rather than `id`? or (c) the API needs to be updated to account for this change in name?

I think b)?

**Comment by denislepage** [comment]
OK, not sure why the re-deploy didn’t stick.

We have changed the response field to nodeDataID, but I think we should also change the request field to also match nodeDataID. I’ve also made a change, so your request should also use nodeDataID now.

So, the answer is a, b and c, for both receiver and tag_project.

I’ve deployed again, and restarted the API server manually to be sure.

**Comment by pmorrill** [comment]
OK - Denis fixed the query to match the changes in the views. Thanx

Regarding #1: we have no table to query for sample node data, so I cannot even retrieve the field names easily without storing them in the java code, or using some sort of dummy query on legit data. Therefore, I return an empty json structure, rather than a set of empty (field) attributes. I hope this can be handled in the R-code - and interpreted as no data?

**Comment by cjardine-bsc** [comment]
Hi guys, sorry I've not been paying as much attention to this as I should!

I suspect the problem is that projectID is missing from vwR_Node_data_for_receiver query. I've added it, hopefully that will resolve that error. 

Cheerio!

**Comment by pmorrill** [comment]
> One outstanding issue:

    With user steffilazerte and receivers SG-3115BBBK1127, SG-3115BBBK0782, and SG-3115BBBK0782 I still get the error "You do not have permission to access the data for this project or receiver. Please contact Motus support." ONLY when accessing the nodeData (https://sandbox.motus.org/api/sgdata/custom/nodes_for_receiver).

This error is perplexing. The msg should be generated before the sub-function that loads node data runs. It shouldn't be directly related to the node data call itself.

I will try to take a look at this today.

**Comment by pmorrill** [comment]
The nodes_for_reciever call requires a valid batch ID, which sounds a little strange, but in fact, it works the same way as the gps_for_receiver call. It is not meant to be called on its own, but as part of a batch query.

I'd say try to work it in just like the gps_for_receiver call, and it should work. If this is not how it was intended to be used, we will adjust it.

BTW: I still have not added documentation for the 2 'node' data entrypoints.

**Comment by denislepage** [comment]
Correct, the intent was to have the node data pulled individually for each batch, like with GPS (and unlike activity).

Steffi, can you confirm that this is now working now that Catherine has added a project ID?

**Comment by steffilazerte** [comment]
> @pmorrill 
> The nodes_for_reciever call requires a valid batch ID, which sounds a little strange, but in fact, it works the same way as the gps_for_receiver call. It is not meant to be called on its own, but as part of a batch query.

Understood, I do give it a `batchID`, starting with 0 because [above](https://github.com/MotusDev/Motus-TO-DO/issues/528#issuecomment-537952834) you said that receivers required it `batchID` and paginated with `id` (now `nodeDataId`) 

> @denislepage 
> Steffi, can you confirm that this is now working now that Catherine has added a project ID?

No, no matter what I do (see below) nothing has changed, I still get an error ONLY for `nodeData`

### Trouble shooting
I'll try to give you every detail of the call to help troubleshoot the problem. Below are all the details and the json query sent to the server as well as the error/json object returned for both projects and receivers. 

In every example user is `steffilazerte`

**Receivers**
Receivers API: "custom/nodes_for_receiver"

- SG-3115BBBK0782
    - With `projectID`: `{"authToken":"XXX","dataVersion":2,"projectID":"SG-3115BBBK0782","batchID":0,"nodeDataId":0}`
    - Without `projectID`: `{"authToken":"XXX","dataVersion":2,"batchID":0,"nodeDataId":0}`
    - Either way server returns error: `You do not have permission to access the data for this project or receiver. Please contact Motus support.'`
    - I also tried using `deviceID` {"authToken":"XXX","dataVersion":2,"deviceID":630,"batchID":0,"nodeDataId":0}
    - But got the same error as above (even if I used "projectID":630)

- Identical results for SG-3115BBBK1383 and SG-3115BBBK1127



**Project**
Projects API: "custom/nodes_for_tag_project"

- Project 4
    - With `projectID` (required)
    - `{"authToken":"XXX","dataVersion":2,"projectID":4,"batchID":0,"nodeDataId":0}`
    - API returns: `{\"projectID\":[],\"nodeDataID\":[],\"batchID\":[],\"ts\":[],\"nodeNum\":[],\"ant\":[],\"sig\":[],\"battery\":[],\"temperature\":[]}`
    - This is good! No problems

**Comment by pmorrill** [comment]
> With projectID: {"authToken":"XXX","dataVersion":2,"projectID":"SG115BBBK0782","batchID":0,"nodeDataId":0}
> Without projectID: {"authToken":"XXX","dataVersion":2,"batchID":0,"nodeDataId":0}

The first is not valid: you have passed a receiver id as a projectID attribute.

The second is correctly formatted, but still not valid: the batchID you send must be linked to a receiver (so must be non-zero). 

When a batchID comes in, the code links it to a receiver and verifies that you can access that receiver. The error you see is expected, there is no verified receiver associated with that batchID. Of course, it would be nice if it sent back an error telling you the batchID must be set. We'll work at improving error messages.

**Comment by pmorrill** [comment]
BTW: Catherine's changes (adding a projectID) are not going to solve this issue. There is no need for a projectID in the nodeForRecievers view, for filtering purposes.

All that is needed is a query with a valid batchID (linked to a receiver to which you have access).

**Comment by steffilazerte** [comment]
@pmorrill Ugh, of course, I misunderstood what you meant by valid `batchID` (i.e. existing in the batches table and non-zero!), I was thinking valid in the terms of being present and an integer. 

Having understood, it was a quick fix to my code. Thanks for your patience!
