### ISSUE TITLE
API:  tag/deploy failing with internal error

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#74]
Calling this API:

```
https://motus.org/api/tag/deploy
```

with this `json` payload:

```JSON
{"serno":"SG-0815BBBK1352",
"hash":"XXX",
"date":"20170928114435",
"fmt":"json",
"login":"john",
"pword":"XXX",
"tagID":27304,
"projectID":161,
"status":"pending",
"tsStart":1504224000.0,
"deferTime":0.0,
"speciesID":19650,
"ts":1506599079.697}
```

I get
```JSON
{"version":"2.0",
"errorCode":"database-error",
"errorMsg":"A database error occurred - org.bsc.exceptions.DBException"}
```

~~Because this is failing, the following tag deployments need to
be done manually:~~
 - ~~tags 27304...27311 (i.e. 8 tags)~~
 - ~~project 161~~
 - ~~start date 2017-09-01 (i.e. 1504224000)~~
 - ~~species RUBL (i.e. 19650)~~

**Update** these calls were retried against the beta server per Paul's suggestion, and all succeeded.

**Comment by pmorrill** [comment]
This seems to be working against the beta server and not the live server. We deployed to live 2 days ago, and the live branch code looks ok. Do we need to restart the api context in live?

**Comment by denislepage** [comment]
I'll give that a try today.

D



-------- Original message --------

**Comment by denislepage** [comment]
I republished the live branch and restarted the server (again?).

You can try and see if it works now.

Denis

**Comment by jbrzusto** [comment]
Still not working.   I re-ran with against the beta and it created a duplicate
deployment for tag 27304 (which should be deleted - deployID is 14665),
but when I tried on the main server, it failed with an internal error again.

(Also, does the motus.org interface not provide a way to delete a tag deployment?  I can't find it.)

**Comment by pmorrill** [comment]
John: the delete deployments tool will be in the next beta release, sometime in Oct. It will only be available to administrators at this point;

Denis: can you forward any exceptions that you saw at 3:50 or so yesterday?

**Comment by jbrzusto** [comment]
Working now.
