### ISSUE TITLE
missing activity data

### ISSUE THREAD

**Issue by ajmacdonald3** [MotusDev/Motus-TO-DO#794]
I'm linking noise data from the `activity` table to each run in the `runs` table to look at potential diagnostic variables for false positives and some runs appear not to have any associated data in the `activity` table. For example:

```
db <- tagme(153, new = F, update = F, forceMeta = F, dir = "sql-databases/")

# get activity table
a <- tbl(db, "activity")

adf <- a %>% 
  collect %>% as.data.frame                                               
rm(a)

# get runs table
r <- tbl(db, "runs")

rdf <- r %>% 
  collect %>% as.data.frame %>% 
  mutate(hourBin = round(tsBegin/3600, 0))                               
rm(r)

# join runs and activity tables to get hourly values on runs/recv for each runID
radf_all <- left_join(rdf, adf, by = c("batchIDbegin" = "batchID", "ant", "hourBin"))

length(unique(radf_all$runID))
[1] 26703

radf_complete <- inner_join(rdf, adf, by = c("batchIDbegin" = "batchID", "ant", "hourBin"))

length(unique(radf_complete$runID))
[1] 24486

radf_missing <- anti_join(rdf, adf, by = c("batchIDbegin" = "batchID", "ant", "hourBin"))

length(unique(radf_missing$runID))
[1] 2217

head(radf_all %>% filter(runID %in% radf_missing$runID))
     runID batchIDbegin    tsBegin      tsEnd done motusTagID ant len nodeNum motusFilter hourBin motusDeviceID year
1 17340905       267136 1503524119 1503524150    1      24423   3   4    <NA>           1  417646            NA   NA
2 18056033       270345 1502372849 1502373281    1      24427   1  41    <NA>           1  417326            NA   NA
3 18056034       270345 1502373374 1502373477    1      24427   1   5    <NA>           1  417326            NA   NA
4 18627492       276056 1499661772 1499661824    1      24429   2   2    <NA>           0  416573            NA   NA
5 18627493       276056 1499661958 1499662534    1      24429   2  31    <NA>           1  416573            NA   NA
6 21112524       309049 1503521101 1503521296    1      24423   3  17    <NA>           1  417645            NA   NA
  month day numTags pulseCount numRuns numHits run2 run3 run4 run5 run6 run7plus
1    NA  NA      NA         NA      NA      NA   NA   NA   NA   NA   NA       NA
2    NA  NA      NA         NA      NA      NA   NA   NA   NA   NA   NA       NA
3    NA  NA      NA         NA      NA      NA   NA   NA   NA   NA   NA       NA
4    NA  NA      NA         NA      NA      NA   NA   NA   NA   NA   NA       NA
5    NA  NA      NA         NA      NA      NA   NA   NA   NA   NA   NA       NA
6    NA  NA      NA         NA      NA      NA   NA   NA   NA   NA   NA       NA
```

In this case, it appears that 2217 runs don't have data in the `activity` table that I can link by `batchID`, `ant`, `hourBin`. Any idea why this would be happening? Would it be something to do with deprecated batches?

**Comment by Hussell** [comment]
Part of it seems to be due to round(tsBegin/3600, 0). It looks like hourBin is calculated by truncating (rounding down) tsBegin/3600. E.g. 1503524119/3600 = 417645.58861 -> 417645 instead of 417646.

**Comment by ajmacdonald3** [comment]
Thanks @Hussell, yes, using `floor(tsBegin/3600)` instead of `round` solved the issue. I pulled the `hourBin = round(tsBegin/3600, 0)` from the code for the [`filterByActivity` function](https://github.com/MotusWTS/motus/blob/master/R/filterByActivity.R) - I wonder if this issue is happening with that function? A quick look with this project's data yielded 11 runs with different probabilities of being true using `round` vs `floor` in the underlying code for the `filterByActivity` function.

**Comment by denislepage** [comment]
Hourbins are definitely calculated with a floor function. If the R package uses a round, it will create problems (for roughly half the records being in the wrong hour bin). @steffilazerte  may need to redeploy the R package with a fix, if that's the case.

**Comment by steffilazerte** [comment]
Okay was exactly what you all thought (round instead of floor), I've fixed it and it should work now as expected now, thanks for pointing that out!

**Comment by denislepage** [comment]
Thanks! Could I also ask you to clean up a bit the sandbox branch. I suspect it’s far behind the master at this point and probably needs to be deleted or replaced by a new branch based on the current master.

**Comment by steffilazerte** [comment]
Already done ;) I just have a couple of tweaks to add in from a recent test fix to master, but other than that it's up-to-date.

**Comment by steffilazerte** [comment]
This fix was pushed to the `beta4` branch. Can someone confirm that it now acts as expected? If so, we can close this issue and consider merging beta4 with master.

**Comment by jsayers-bsc** [comment]
I'm seeing something similar with a receiver on project 287. There is antenna activity in the [Receiver Timeline](https://motus.org/data/receiver/timeline?year=2020&id=3395) but no activity downloaded via the R package later than 2020-09-04.

```
m <- tagme('SG-4940RPI33FB7', new = F, update = T, forceMeta = T, dir = '../Data')
Checking for new data for receiver SG-4940RPI33FB7 (deviceID: 1506)
activity:     4 batch records to check
batchID  1296586 (#     1 of      4): got      4 activity records
Downloaded 4 activity records
nodeData:     0 batch records to check

# activity table
a <- tbl(m, 'activity') %>% collect() %>% as.data.frame() 

# most recent date in activity table
max(as.Date(paste(a$year, a$month, a$day, sep = '-')))
[1] "2019-09-04"
```


The receiver was active and recording data from May to August 2020, but nothing shows up in the R data. 

Looks like there are only 3 batches with associated activity yet there are 40 batches in the batches table (and 87 batches in the db?).

```
distinct(a, a$batchID)
  a$batchID
1   1086441
2   1086450
3   1296586
```

This is with motus R package version ‘4.0.1.9999’

**Comment by steffilazerte** [comment]
Looking into this from the R side, there actually isn't a problem (unless it's the slightly ambiguous messages). 

Here, `tagme()` is only checking 4 records because it's resuming the run so only checking new batches (unfortunately if there are lots of batches with zero, currently the function backs up to the last batch with activity and restarts from there, so we'll always get this message, even if there are no actual "new" records)

To double check, you can re-download all the activity data from scratch using the `activity()` function:

```
m <- tagme('SG-4940RPI33FB7', new = F, update = T, forceMeta = T, dir = '../Data')
activity(m)
```

BUT you won't get any more records than before. The function is checking against the server, but only three batches on the server actually returned activity... In `beta4` I've altered the messages so they return a status message for all batches (even those that had no activity) to make that a bit more clear.

I've also changed the message to use the word "new", if the process is resuming (i.e. `activity:     4 new batch records to check`) so hopefully that clarifies things. 

If there are still missing activity records, then I think this is a server/API issue.

**Comment by steffilazerte** [comment]
Is this still an issue?

**Comment by jsayers-bsc** [comment]
- Yes that message re the activity records is a bit confusing! There is no new data for this receiver, so there shouldn't be new activity records to be downloaded. But they're being downloaded again anyway due to the how the client is downloading data?

- The issue of missing activity that I mentioned is still an issue with v 4.0.2. But now I'm not sure it's related to the underlying cause above (round vs floor). There is a huge mismatch between the activity present in the data download in R and what is displayed in the receiver timeline. I think I should post that particular one in a new issue.

**Comment by steffilazerte** [comment]
I from what I can see, the data isn't being returned by the server, so I think that's a database/api issue, so I agree, I'll close this and you can open a new issue to keep things under control :smile:

As for the problem with the "new" activity records (I've opened a new issue to hopefully deal with this #841), the batchID of the last activity is used as the resume point... so if batchIDs after that one didn't have activity data, there's no record of it and the next check will always re-check those batchIDs. The obvious fix is to store the last batchID checked, but where that should be stored is another matter.
