### ISSUE TITLE
Remove RUBL's from public view - Deployment 5891

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#853]
https://motus.org/data/receiverDeployment?id=5891

Likely aliasing

**Comment by Hussell** [comment]
@cjardine-bsc, is the correct way to do this just to do an insert into det_runs_filters?

<pre>
insert into det_runs_filters values
(1157110,71596032,35156,0),
(1157110,71596186,35154,0),
(1157110,71607504,35156,0),
(1157110,71609905,35156,0),
(1157110,71609953,35154,0),
(1157110,71609954,35154,0),
(1157110,71610084,35158,0),
(1157110,71614156,35155,0),
(1157110,71615656,35156,0),
(1157110,71616038,35154,0),
(1157111,71620312,35157,0)
</pre>

**Comment by leberrigan** [comment]
Ipswich Sparrows, Kestrel, PUMA, Nighthawk:
https://motus.org/data/receiverDeploymentDetections?id=6056

Lewis's Woodpecker + Tricoloured Blackbird:
https://motus.org/data/receiverDeploymentDetections?id=6057

Nighthawk + Lewis's Woodpecker
https://motus.org/data/receiverDeploymentDetections?id=6043

Ipswich Sparrows, WESA, PUMA, Nighthawk:
https://motus.org/data/receiverDeploymentDetections?id=6044

Tricoloured Blackbird:
https://motus.org/data/receiverDeploymentDetections?id=6047

Ipswich Sparrows, Kestrel, Tricoloured Blackbird:
https://motus.org/data/receiverDeploymentDetections?id=6049

...and more!

**Comment by jsayers-bsc** [comment]
I also just received a request to hide all of [these ](https://motus.org/data/receiver/deployment/detections/timeline?year=2020&id=5922)as they all have very questionable movement patterns and none have runLen > 4.

![image](https://user-images.githubusercontent.com/55001144/98977630-d2a46800-24e6-11eb-8b1b-f13585a3e526.png)

This is a job for #749!

**Comment by cjardine-bsc** [comment]
Okay. I did some things in sandbox. This is mostly an update for now. 

I've created a new table (sigh) called det_runs_filters_manual that will allow us to manually add tag/station combos to the motus filter. 

I've expanded the det_runs_filter table with three columns that will help us keep track of why a run has been flagged as bad. runLen, noise, manual (we'll add species range to this when we get there). There is still the option to change this to track by rows instead of columns, but for the moment this will allow us to track it without breaking any of our other processes (UPDATE I may already regret this, it's going to make it tricky to delete and re-insert based on runID, will revisit tomorrow).

I've altered the existing prSGBatchesActivityBatchID proc to update those columns. 

I've created a new proc called prSGBatchesRunFiltersBatchID this will be called as part of  prTaghitsSummariesBatchID when new batches are imported. 


Pending issues:

1. Should we really be using tagID, or should we instead use tag_deploy_id? It's rare but tags are sometimes recovered and re-deployed on a different species or region. 
2. I need to expand the prTaghitsDeployIDXXX procs to deal with updating the det_runs_filter table when they are run (the new proc relies on det_taghits_runs to determine which runs match the tag/station combos we've flagged as errors). I may actually do this with an after update/delete trigger on det_taghits_runs. That what tomorrow-Catherine will likely work on. 

Next steps. 

For now, this is just in sandbox, particularly since it's going to rely on the station concept, though I don't think it would be much work to transfer this over to live using station_deployments for the time being. It would be handy if @jsayers-bsc  @leberrigan @StuMackenzie could keep a list of tag_ids and sensor_deployments (I'll change these over to station_ids based on what I've done in sandbox) that you want manually filtered out. That would be a bit cleaner than the scrapbook above. 

When we're working on new summaries and tools we should be considering how we will allow admins or users to flag these problematic tags/stations themselves and whether that needs a review process. 

@Hussell you're welcome to test inserting into det_runs_filters_manual via an admin-only button push on some of your summary pages if you'd like. We could discuss on Thursday.

**Comment by leberrigan** [comment]
What do we do about situations like this: https://motus.org/data/receiver/deployment/plot/SG%2D3214BBBK5757-2017%20Quebec%2C%20Tadoussac%20%2D%20Andr%E9.png?id=3454&n=100&firstTag=0

Huge number of false positives as a result of noise.

**Comment by cjardine-bsc** [comment]
I'm ready to test this in live once you have some tag_deploy_id and sensor_deploy_ids for me.

**Comment by ajmacdonald3** [comment]
Along the lines of what Lucas suggested and what Stu was saying earlier about keeping it simple, I wonder if it would be worth just excluding all detections from recvDeployIDs that are clearly problematic? In my experience with filtering, I find noisy receivers with a ton of false detections of many tags during a certain period more common than problematic tags where all the detections of that tag are false (with the notable exception of those CTT tags). We run the risk of hiding a few real detections in the public outputs, but it would likely be more efficient than going through each tag separately and all the data would still be there when downloaded in R.

**Comment by leberrigan** [comment]
Even if we remove noisy stations from all tracks we would still want the option to explore those stations. That means we'd still have to find a way to remove false positives from those pages. Besides noise, we also have a lot of tag aliasing going on, like at [Bahia Caulin](https://github.com/MotusDev/Motus-TO-DO/issues/667) so I still don't see a way out from the ol' case-by-case.

---

Let's give these ones a go!

Tag Deploy ID | Receiver Deploy ID
-- | --
27254 | 3454
21396 | 2729
21397 | 2729
21399 | 2729
22380 | 2729
22057 | 2729
25228 | 2729
25236 | 2729
23122 | 2729
23137 | 2729
23140 | 2729
21879 | 2729
21885 | 2729
20908 | 2729
20909 | 2729
20913 | 2729
26264 | 2729
26265 | 2729
26269 | 2729
26284 | 2729
26288 | 2729
21500 | 2729

**Comment by denislepage** [comment]
There are likely cases where this makes sense, though it may be also useful to only exclude a range of date for instance.

As mentioned on the call today, we also have another process to flag noisy eceivers, but this perhaps this can supercede it.

I would certainly feel more bullish if we allowed people to toggle filtered detections in or out on the results pages.

**Comment by jsayers-bsc** [comment]
| tag_deploy_id | sensor_deploy_id|
|-----------------|-----------------|
 8386  | 3191
8386 | 2732

**Comment by cjardine-bsc** [comment]
Okay, I've added filters for those combos as a test. I think the tracks are recalculated once a day, so we should see them updated tomorrow. Check it out and let me know if that seems to have the desired effect.

**Comment by cjardine-bsc** [comment]
A reminder to @jsayers-bsc and @leberrigan to give this a test before tomorrow's meeting. :-)

**Comment by leberrigan** [comment]
Okay well way to go Lucas. I just realized I was using the Motus tag ID rather than the deployment ID! Ugh.. Silly me assumed the numbers listed on the [receiver deployment plot](https://motus.org/data/receiver/deployment/plot/SG%2D3214BBBK6103-2015%20MotusON%2C%20Koffler.png?id=2729&n=100&firstTag=0) were the deployment ID. Why would I think that? 

I checked the track that Josh gave and it doesn't seem to have changed:
https://motus.org/data/track?tagDeploymentId=8386


I'll get those deployment IDs and list them here:

**Comment by cjardine-bsc** [comment]
That's what these tests are for! 

I can reverse the above and I'll await a nice new list with tag_deploy_ids instead :-)

**Comment by jsayers-bsc** [comment]
Yeah the WTSP tracks are still there. I believe those ones were tag_deploy_id as well.

**Comment by cjardine-bsc** [comment]
Oh I removed all the filters. 

You're saying these two are good to go?


8386 | 3191
-- | --
8386 | 2732

**Comment by cjardine-bsc** [comment]
Okay, I should have added filters for those two combos.

**Comment by jsayers-bsc** [comment]
Hmm, those WTSP tracks are still there. 

tag deployment: https://motus.org/data/tagDeployment?id=8386
receiver deployment: https://motus.org/data/receiverDeployment?id=3191

**Comment by cjardine-bsc** [comment]
Welp....that was not the goal! 

Ahhhh, I didn't run the summaries to update taghits_daily, these pages must pull from there. Okay, I've run those for these batches. Abra kadabra! Poof! Bye bye Sparrow! 

For our next trick we shall re-run those receivers and see if those pesky sparrows stay disappeared!

For that  we will need the Teller to my Pen! @Hussell, can you re-run these batches? Thanks!


234736
--
234739
234740
234741
234747
234748
234750
234751
234752
234755
234756
234757
234761
234762
234763
234764
234765
279559
279560
279561

**Comment by jsayers-bsc** [comment]
The sparrows are no more.

Here are a couple others — nighthawks which very briefly visited BC.

Tag Deploy ID | Receiver Deploy ID
-- | --
25185 | 5511
28152 | 5511
28152 | 5977


In fact both of these tags are quite problematic: 

https://motus.org/data/track?tagDeploymentId=25185
https://motus.org/data/track?tagDeploymentId=28152

**Comment by cjardine-bsc** [comment]
#746

Adding a reference to this.

**Comment by leberrigan** [comment]
I haven't seen changes for the tags I listed, but I realize now that maybe you missed them since I only edited the previous post. 

Here there are!

Tag Deploy ID | Receiver Deploy ID
-- | --
13648 | 2729
13649 | 2729
13651 | 2729
13653 | 2729
13658 | 2729
13668 | 2729
9387 | 2729
15196 | 2729
15222 | 2729
15225 | 2729
15239 | 2729
15241 | 2729
15251 | 2729
15255 | 2729
15256 | 2729
15259 | 2729
15272 | 2729
15281 | 2729
15284 | 2729
15292 | 2729
15294 | 2729
15297 | 2729
15299 | 2729
15300 | 2729
15311 | 2729
15320 | 2729
15335 | 2729
15345 | 2729
15358 | 2729
15379 | 2729
15389 | 2729
15399 | 2729
15407 | 2729
15414 | 2729
15415 | 2729
15417 | 2729
15421 | 2729
15424 | 2729
15425 | 2729
15427 | 2729
15429 | 2729
10275 | 2729
10283 | 2729
10285 | 2729
10286 | 2729
10299 | 2729
10301 | 2729
9653 | 2729
9657 | 2729
9660 | 2729
8412 | 2729
8188 | 2729
8197 | 2729
6602 | 2729
11069 | 2729
11074 | 2729
11076 | 2729
11078 | 2729
11922 | 2729
11925 | 2729
11927 | 2729
13751 | 2729
13754 | 2729
13755 | 2729
13758 | 2729
13762 | 2729
13779 | 2729
13783 | 2729
13785 | 2729
13786 | 2729
13787 | 2729
13788 | 2729
13801 | 2729
13803 | 2729
13804 | 2729
13814 | 2729
13815 | 2729
13817 | 2729
13821 | 2729
13838 | 2729
20990 | 2729
21029 | 2729
21037 | 2729
21078 | 2729
21083 | 2729
21085 | 2729
21093 | 2729
21103 | 2729
21130 | 2729
21368 | 2729

**Comment by cjardine-bsc** [comment]
Okay, I've implemented for the nighthawks and for Lucas's list. If you're happy with those results than this is set up and ready to go! 

I've created a trigger and proc so that every time you enter a new record into the det_runs_filters_manual table it will go through and update the filters and clean up the summary data. Check to make sure you're happy with the filtering results for the above and if you are we can set you up to enter your records directly in the table. 

Currently I'm not supporting time periods, that will be an additional feature we can look at adding. But my next priority is looking at filtering using the ebird checklists which will help with some of Elizabeth's work.

**Comment by StuMackenzie** [comment]
Just closing loops/understanding/clarification. Forgive me if I’ve missed this.

1) How, or are these flags translated into the data available through the R package?

2) Where is the documentation for the ‘Motus filter’ that users could reference?

3) if/when eBird filter is implemented  we should write or update any documentation in the RBook and a short notice/reminder to the Motus list



____________________

**Comment by StuMackenzie** [comment]
Also, thank you Catherine!

Luc, should add populating this table to Hannah’s list. Should also get her on git so we can tag her etc. apologies if she’s already on.


____________________

**Comment by cjardine-bsc** [comment]
1) How, or are these flags translated into the data available through the R package?

They will be flagged as problematic in the motusFilter column of the R package. BUT, right now there is no indication that these were filtered manually instead of due to run length. Lets discuss if/how we want that level of detail translated into R. 

2) Where is the documentation for the ‘Motus filter’ that users could reference?

Chapter 5.4.1. of the R book. Right now the description doesn't include any detail about manual filtering. 

3) if/when eBird filter is implemented  we should write or update any documentation in the RBook and a short notice/reminder to the Motus list

Agreed! I'll keep you posted as I start working my way through it.

**Comment by jsayers-bsc** [comment]
> The sparrows are no more.
> 
> Here are a couple others — nighthawks which very briefly visited BC.
> 
> Tag Deploy ID	Receiver Deploy ID
> 25185	5511
> 28152	5511
> 28152	5977
> In fact both of these tags are quite problematic:
> 
> https://motus.org/data/track?tagDeploymentId=25185
> https://motus.org/data/track?tagDeploymentId=28152

I just noticed that some of these are still here. Well sort of. They are absent from the map online, but still present when I query det_taghits_tracks. Maybe this is expected and they are being filtered out downstream of taghits_tracks? 

(This is tag deployment 25185 and sensor deployment 5511 BTW)

**Comment by StuMackenzie** [comment]
See - https://github.com/MotusDev/Motus-TO-DO/issues/668

ACTION - detailed public documentation of what's included in the 'Motus filter' and flagging on the website wherever public data is shown.

**Comment by StuMackenzie** [comment]
Note https://github.com/MotusDev/Motus-TO-DO/issues/855

**Comment by StuMackenzie** [comment]
Original CTT False Positive Discussion - https://github.com/MotusDev/Motus-TO-DO/issues/659

**Comment by cjardine-bsc** [comment]
documentation note here: All CTT runs of len= 1 are now flagged in the motus filter.

**Comment by denislepage** [comment]
Great (as a first step)! We may find that it’s sufficient, too.

**Comment by jsayers-bsc** [comment]
tag_deploy_id | sensor_deploy_id |   | comments
-- | -- | -- | --
5673 | 5856 |   | 1 of 4 NSWO “detected” over a few days in the high arctic
5670 | 5856 |   | 1 of 4 NSWO “detected” over a few days in the high arctic
5668 | 5856 |   | 1 of 4 NSWO “detected” over a few days in the high arctic
5665 | 5856 |   | 1 of 4 NSWO “detected” over a few days in the high arctic
5667 | 3869 |   | NSWO far outside range (briefly in Colombia)
5667 | 3713 |   | NSWO far outside range (IN Chile)
5667 | 3857 |   | NSWO far outside range (IN Chile)
13031 | 3869 |   | NSWO far outside range (briefly in Colombia)
13031 | 3713 |   | NSWO far outside range (IN Chile)
13031 | 3857 |   | NSWO far outside range (IN Chile)
5667 | 3191 |   | NSWO at SELVA tagging location
5679 | 3191 |   | NSWO at SELVA tagging location
5682 | 3191 |   | NSWO at SELVA tagging location

**Comment by cjardine-bsc** [comment]
> 
> 
> Welp....that was not the goal!
> 
> Ahhhh, I didn't run the summaries to update taghits_daily, these pages must pull from there. Okay, I've run those for these batches. Abra kadabra! Poof! Bye bye Sparrow!
> 
> For our next trick we shall re-run those receivers and see if those pesky sparrows stay disappeared!
> 
> For that we will need the Teller to my Pen! @Hussell, can you re-run these batches? Thanks!
> ## 234736
> 
> 234739
> 234740
> 234741
> 234747
> 234748
> 234750
> 234751
> 234752
> 234755
> 234756
> 234757
> 234761
> 234762
> 234763
> 234764
> 234765
> 279559
> 279560
> 279561

Reminder to @Hussell to test this by re-running this receiver. Before Thursday ideally. Thanks bunches.

**Comment by cjardine-bsc** [comment]
> 25185

I looked at this. There is one record in det_taghits_tracks for this deployment pair:

SELECT * FROM [det_taghits_tracks]
where tagDeployId = 25185 and latitude = 49.15000000

It is the start of the track, but there are not subsequent entries. I double checked and det_taghits_runs has all runs filtered for this pair, so it probably somewhere in the track generation tool that is still leaving in the start of the track. @Hussell

**Comment by cjardine-bsc** [comment]
> 
> tag_deploy_id 	sensor_deploy_id 	  	comments
> 5673 	5856 	  	1 of 4 NSWO “detected” over a few days in the high arctic
> 5670 	5856 	  	1 of 4 NSWO “detected” over a few days in the high arctic
> 5668 	5856 	  	1 of 4 NSWO “detected” over a few days in the high arctic
> 5665 	5856 	  	1 of 4 NSWO “detected” over a few days in the high arctic
> 5667 	3869 	  	NSWO far outside range (briefly in Colombia)
> 5667 	3713 	  	NSWO far outside range (IN Chile)
> 5667 	3857 	  	NSWO far outside range (IN Chile)
> 13031 	3869 	  	NSWO far outside range (briefly in Colombia)
> 13031 	3713 	  	NSWO far outside range (IN Chile)
> 13031 	3857 	  	NSWO far outside range (IN Chile)
> 5667 	3191 	  	NSWO at SELVA tagging location
> 5679 	3191 	  	NSWO at SELVA tagging location
> 5682 	3191 	  	NSWO at SELVA tagging location

Added to the filters. @jsayers-bsc can you check the web outputs and make sure they are as expected?

**Comment by cjardine-bsc** [comment]
Problem windows/receivers (with potential whitelist) provided by Adam. I'm holding off adding these to the filters right now until we have a discussion on Thursday about how course vs fine we want to try and accommodate with these manual filters. 


Receiver | Deployment ID | Date start | Date end | Local TagProject
-- | -- | -- | -- | --
SG-3115BBBK1383 | 2878 | 2018-04-04 | 2018-04-04 | 51
SG-2013BB000060 | 5505 | 2019-08-07 | 2018-09-02 | 4
SG-32FDRPI3CB45 | 5062 | 2019-10-26 | 2019-12-06 | 4
SG-32FDRPI3CB45 | 5062 | 2020-09-30 | 2020-09-30 | 4

**Comment by jsayers-bsc** [comment]
> Added to the filters. @jsayers-bsc can you check the web outputs and make sure they are as expected?

They are gone from the summary tables and the _individual_ maps on the deployment overview page. However some are still in the det_tagshits_tracks and the tracks map if accessed another way on Motus.org. A couple are present with only 1 record, but for others there are multiple records. 

e.g.

**Deployment 5668** 

No more Baffin Island in the summary table or the map on the tag deployment summary: https://motus.org/data/track?tagDeploymentId=5668

But there is still one record in det_taghits_tracks 

select * from det_taghits_tracks where tagDeployId = 5668 and latitude > 70

_And_ it is shown on this map: https://motus.org/data/tracksMap?t=5668

OR

**Deployment 5673**

No more Baffin Island in the summary table or the map on the tag deployment summary: https://motus.org/data/track?tagDeploymentId=5673

Multiple records in det_taghits_tracks

select * from det_taghits_tracks where tagDeployId = 5673 and latitude > 70

Once again Baffin is also shown at this map: https://motus.org/data/tracksMap?t=5673

**Comment by cjardine-bsc** [comment]
Okay, that sounds good. 

ComputeTracks was run yesterday at 3pm EST.  There is another open issue asking @Hussell to look into why some of these tags are showing up there.

**Comment by cjardine-bsc** [comment]
So, I took a look at the document that Amie shared with me where they looked at the number of missed bursts within a run. As discussed the concept is nice and simple:

Duration = max_ts-min_ts
nPred: Number pulses predicted = duration/period 
nMiss: Number of pulses missed = predicted-run_len
probMiss - nMiss/nPred

In the document that Amie and Bianca have been developing they are suggesting that any value over 0.75 would indicate a bad run and any under 0.25 would be a good run.  

I applied this calculation to the entire det_taghits_runs table in sandbox (it only took 7minutes) I decided to run the same on live since it is so fast. 

I also did a few summaries to look at how our current filtering compares to this new measure. 

We are filtering out 7million runs that have a probmiss of 0.25 (not too surprising given we blanket filter out runs of len <=3)
We are not filtering out 1.5million runs hat have a probmiss > 0.75. This is where potential improvements to post processing filtering could be made. 

We can now do a little comparison between the data this would flag and what we expect are bad vs good runs. Is Hannah on github? If there are specific receivers she'd like to look at I can pull those for her and we can sanity check whether I should filter any runs with a probMiss > 0,75 (or a refined value) out of the public outputs.

**Comment by denislepage** [comment]
Small tweak. nPredicted is = (duration/period) + 1

This wasn’t totally clear:

We are filtering out 7million runs that have a probmiss of 0.25 (not too surprising given we blanket filter out runs of len <=3)

You presumably you mean smaller than 0.25. As you say, the proportion on small runs is not smoothly distributed. Perhaps an interesting stats would be to look at the distribution of the missed pulses by run length, in absolute numbers. The very short runs with very few missed bursts are perhaps worth looking at. I suspect there’s still a lot of noise in there. Finding out may be difficult.

A run length of 2, in theory could have up to about 18 missed bursts. I’m curious what the pattern is, and whether shorter runs are proportionally showing more missed bursts than longer runs. Logically, I would expect so (short runs = bad, missed bursts = bad).

A similar stats would be a plot showing the average number and the 95% range of missed bursts per run length.

The 1.5 million runs with > 75% missed burst (but len > 3) is the golden goose in this case, as you say. Knowing the run length distribution of those would also be interesting. How many 4, 5, 6, etc.

**Comment by StuMackenzie** [comment]
I've invited Hannah. You can also discuss in Slack - #public-data-filters., but we should make sure that important documentation is captured here.

**Comment by cjardine-bsc** [comment]
RE:  Small tweak. nPredicted is = (duration/period) + 1 

I'm using ceiling(duration/period) but yes. 

RE: You presumably you mean smaller than 0.25.

Correct. 

RE A run length of 2, in theory could have up to about 18 missed bursts

As an FYI. According to Amie's document tagfinder allows up to 60 missed bursts. "During the process of automated tag filtering up to 60 bursts can be missed without the run being terminated for the identified tag"
 
RE: Perhaps an interesting stats would be to look at the distribution of the missed pulses by run length, in absolute numbers. 

That would be neat. I'll find some time to make up a few plots while Hannah sanity checks whether the probMiss value seems informative for identifying known bad data.

**Comment by denislepage** [comment]
Not sure ceiling is safe. If that period = 4.1, the run length is 8.2 (should always be a multiple of the period), but in theory, but it can land on either side due to precision (8.1999 vs. 8.2001) and give you different results.

The point I was making it is if you have 2 full periods, you have an extra burst to add.

8.2 = run length of 3.

To be safe, I’d use: round(duration/period) + 1

60 bursts is a lot more than I expected. That suggests that the cutoff is based on a duration rather than a multiple of the period. It might be worth revisiting the cutoff rules at some point. With CTT, I think I have used 5 minutes, possible while trying to emulate tag finder rules to some degree. Given that most of the CTT tags have a short period (1s), that could even potentially mean 300 missed bursts in those cases. For a 4-5 second Lotek tag, that would match roughly the 60 that Amie and Bianca found. Perhaps we’re fine with this.

**Comment by jsayers-bsc** [comment]
A few more from a swallow tagging site in Saskatchewan

tag_deploy_id | sensor_deploy_id | comment
-- | -- | --
16863 | 5431 | spurious “detection” at site of swallow tagging
6199 | 5431 | spurious “detection” at site of swallow tagging
24666 | 5431 | spurious “detection” at site of swallow tagging
24666 | 5352 | spurious “detection” at site of swallow tagging
24719 | 5352 | spurious “detection” at site of swallow tagging

**Comment by cjardine-bsc** [comment]
> 
> 
> A few more from a swallow tagging site in Saskatchewan
> tag_deploy_id 	sensor_deploy_id 	comment
> 16863 	5431 	spurious “detection” at site of swallow tagging
> 6199 	5431 	spurious “detection” at site of swallow tagging
> 24666 	5431 	spurious “detection” at site of swallow tagging
> 24666 	5352 	spurious “detection” at site of swallow tagging
> 24719 	5352 	spurious “detection” at site of swallow tagging

Added.

**Comment by jsayers-bsc** [comment]
Here are some unnaturally peregrine falcons pointed out by Project 48.

Most occurred at Fincas La Palmeras, a Selva tagging location. One occurred at another Selva station, but the pattern looks different than the typical tagging location (BI is all over the place). 


tag_ceploy_id | sensor_deploy_id | comment
-- | -- | --
24666 | 3872 | site of tagging location (SEVLA; Finca Las Palmeras)
24664 | 3872 | site of tagging location (SEVLA; Finca Las Palmeras)
24665 | 3872 | site of tagging location (SEVLA; Finca Las Palmeras)
24662 | 3872 | site of tagging location (SEVLA; Finca Las Palmeras)
24662 | 7515 | noisy station (unknown reason; possibly due to FCD configuration)
24659 | 3872 | site of tagging location (SEVLA; Finca Las Palmeras)
24666 | 3872 | site of tagging location (SEVLA; Finca Las Palmeras)
24663 | 3872 | site of tagging location (SEVLA; Finca Las Palmeras)
24660 | 3872 | site of tagging location (SEVLA; Finca Las Palmeras)
24658 | 3872 | site of tagging location (SEVLA; Finca Las Palmeras)

**Comment by cjardine-bsc** [comment]
Sure I can add those, does the "site of tagging location" comment mean the tag is unexpectedly far from the deployment location?

Also can you explain what you mean by "BI is all over the place"

**Comment by jsayers-bsc** [comment]
> Sure I can add those, does the "site of tagging location" comment mean the tag is unexpectedly far from the deployment location?

Yes, given the context. Project 48 tagged 8 PEFA and they all showed up at Finca Las Palmeras at the same time as the tagging (and in most cases nowhere else).

> Also can you explain what you mean by "BI is all over the place"

They're Outta control, Jerry! There are a variety of BIs present. Most of the false positives at stations where many physical tags were present are the same BI as those present.

**Comment by cjardine-bsc** [comment]
Added. Note that 

24666 | 3872

Is on the list twice.

**Comment by hanndrake** [comment]
@cjardine-bsc Here's the list of suspect detections up until today! (~150 tags, 11  "problem" stations):

[Compiled_suspect_data_Feb_11_21.xlsx](https://github.com/MotusDev/Motus-TO-DO/files/5968917/Compiled_suspect_data_Feb_11_21.xlsx)

**Comment by cjardine-bsc** [comment]
These have been added. 

> 
> 
> @cjardine-bsc Here's the list of suspect detections up until today! (~150 tags, 11 "problem" stations):
> 
> [Compiled_suspect_data_Feb_11_21.xlsx](https://github.com/MotusDev/Motus-TO-DO/files/5968917/Compiled_suspect_data_Feb_11_21.xlsx)

**Comment by jsayers-bsc** [comment]
tag_deploy_id | sensor_deploy_id |  
-- | -- | --
17451 | 1865 | Obvious aliasing (swallows in the arctic with the same BI as tagged   shorebirds)
17459 | 1865 | Obvious aliasing (swallows in the arctic with the same BI as tagged   shorebirds)
17470 | 1865 | Obvious aliasing (swallows in the arctic with the same BI as tagged   shorebirds)
17476 | 1865 | Obvious aliasing (swallows in the arctic with the same BI as tagged   shorebirds)
17479 | 1865 | Obvious aliasing (swallows in the arctic with the same BI as tagged   shorebirds)
17482 | 1865 | Obvious aliasing (swallows in the arctic with the same BI as tagged   shorebirds)
17667 | 1865 | Obvious aliasing (swallows in the arctic with the same BI as tagged   shorebirds)
17683 | 1865 | Obvious aliasing (swallows in the arctic with the same BI as tagged   shorebirds)
17689 | 1865 | Obvious aliasing (swallows in the arctic with the same BI as tagged   shorebirds)
13031 | 1865 | Obvious aliasing (southern birds with same BI as shorebirds tagged)
14096 | 1865 | Obvious aliasing (southern birds with same BI as shorebirds tagged)
14135 | 1865 | Obvious aliasing (southern birds with same BI as shorebirds tagged)
14219 | 1865 | Obvious aliasing (southern birds with same BI as shorebirds tagged)
15640 | 1865 | Obvious aliasing (southern birds with same BI as shorebirds tagged)
15758 | 1865 | Obvious aliasing (southern birds with same BI as shorebirds tagged)
12598 | 1865 | improbable movement; BCNH in the high arctic
  |   |

**Comment by cjardine-bsc** [comment]
> 
> tag_deploy_id 	sensor_deploy_id 	 
> 17451 	1865 	Obvious aliasing (swallows in the arctic with the same BI as tagged shorebirds)
> 17459 	1865 	Obvious aliasing (swallows in the arctic with the same BI as tagged shorebirds)
> 17470 	1865 	Obvious aliasing (swallows in the arctic with the same BI as tagged shorebirds)
> 17476 	1865 	Obvious aliasing (swallows in the arctic with the same BI as tagged shorebirds)
> 17479 	1865 	Obvious aliasing (swallows in the arctic with the same BI as tagged shorebirds)
> 17482 	1865 	Obvious aliasing (swallows in the arctic with the same BI as tagged shorebirds)
> 17667 	1865 	Obvious aliasing (swallows in the arctic with the same BI as tagged shorebirds)
> 17683 	1865 	Obvious aliasing (swallows in the arctic with the same BI as tagged shorebirds)
> 17689 	1865 	Obvious aliasing (swallows in the arctic with the same BI as tagged shorebirds)
> 13031 	1865 	Obvious aliasing (southern birds with same BI as shorebirds tagged)
> 14096 	1865 	Obvious aliasing (southern birds with same BI as shorebirds tagged)
> 14135 	1865 	Obvious aliasing (southern birds with same BI as shorebirds tagged)
> 14219 	1865 	Obvious aliasing (southern birds with same BI as shorebirds tagged)
> 15640 	1865 	Obvious aliasing (southern birds with same BI as shorebirds tagged)
> 15758 	1865 	Obvious aliasing (southern birds with same BI as shorebirds tagged)
> 12598 	1865 	improbable movement; BCNH in the high arctic
>   	  	 
> 
> some more for you @cjardine-bsc

Done

**Comment by hanndrake** [comment]
@cjardine-bsc A new table of suspect false detections with all our recent finds.

[Compiled_suspect_detection _HD_Mar_5_21.xlsx](https://github.com/MotusDev/Motus-TO-DO/files/6101655/Compiled_suspect_detection._HD_Mar_5_21.xlsx)

**Comment by jsayers-bsc** [comment]
Some more tag/receiver deployment combos for a particular PEFA (flagged by Project 48) @cjardine-bsc 

tag_deploy_id | sensor_deploy_id | comment
-- | -- | --
24662 | 4107 | Suspect detection (flagged by Project 48)
24662 | 3454 | Suspect detections at known noisy site (flagged by Project 48)
24662 | 7521 | Suspect detections at known noisy site (flagged by Project 48)

**Comment by cjardine-bsc** [comment]
> 
> 
> @cjardine-bsc A new table of suspect false detections with all our recent finds.
> 
> [Compiled_suspect_detection _HD_Mar_5_21.xlsx](https://github.com/MotusDev/Motus-TO-DO/files/6101655/Compiled_suspect_detection._HD_Mar_5_21.xlsx)

Added.

**Comment by cjardine-bsc** [comment]
> 
> 
> Some more tag/receiver deployment combos for a particular PEFA (flagged by Project 48) @cjardine-bsc
> tag_deploy_id 	sensor_deploy_id 	comment
> 24662 	4107 	Suspect detection (flagged by Project 48)
> 24662 	3454 	Suspect detections at known noisy site (flagged by Project 48)
> 24662 	7521 	Suspect detections at known noisy site (flagged by Project 48)

Added

**Comment by leberrigan** [comment]
tagID | tagDeployID | recvDeployID | Justification | Reason 
-- | -- | -- | -- | --
12105 | 25236 | 4788 | Lots of PUMA present with the same BI | Type 2 tag aliasing
12097 | 25228 | 4788 | Lots of PUMA present with the same BI | Type 2 tag aliasing
12105 | 25236 | 4798 | Lots of PUMA present with the same BI | Type 2 tag aliasing
12097 | 25228 | 4798 | Lots of PUMA present with the same BI | Type 2 tag aliasing
12083 | 25214 | 4798 | Lots of PUMA present with the same BI | Type 2 tag aliasing
25436 | 33688 | 4798 | Lots of PUMA present with the same BI | Type 2 tag aliasing

**Comment by cjardine-bsc** [comment]
I need tagDeployID not Tag ID. 

Thanks!

**Comment by cjardine-bsc** [comment]
just flagging @leberrigan about the tag_id vs tagdeployId issue above.

**Comment by StuMackenzie** [comment]
More RUBL's to add to the black list  Colombia and Chile detections - https://motus.org/data/tracksMap?t=5511&t=5512&t=5513&t=5514&t=5515&t=5990&t=5991&t=5992&t=5994&t=5995&t=5996&t=5997&t=5998&t=5999&t=6000&t=6001&t=6002&t=6008&t=6009&t=6010&t=6011&t=6012&t=6470&t=6471&t=6472&t=6473&t=6474&t=6475&t=6477&t=6478&t=6479&t=6480&t=6481&t=6482&t=9835&t=9836&t=9837&t=9838&t=9839&t=9841&t=9842&t=9843&t=9844&t=9845&t=9846&t=9847&t=9848&t=9849&t=9850&t=9851&t=9852&t=9853&t=9854&t=9855&t=9856&t=9857&t=9858&t=9859&t=9860&t=9861&t=9862&t=9863&t=9864&t=9865&t=9866&t=9867&t=9868&t=10557&t=11067&t=11068&t=11069&t=11070&t=11071&t=11072&t=11073&t=11074&t=11075&t=11076&t=11077&t=11078&t=11079&t=11080&t=11081&t=11082&t=11083&t=11084&t=11085&t=11262&t=11263&t=11264&t=12407&t=12414&t=12457&t=12535&t=12536&t=12537&t=12930&t=14213&t=14218&t=14220&t=14221&t=14222&t=14223&t=14225&t=14228&t=14229&t=14230&t=14231&t=14232&t=14233&t=14902&t=18654&t=18655&t=18656&t=18657&t=18659&t=18660&t=18661&t=18662&t=19030&t=19031&t=19032&t=19035&t=19036&t=19037&t=19038&t=19039&t=20163&t=20164&t=20165&t=20353&t=20354&t=22928&t=22929&t=22930&t=22933&t=22934&t=22935&t=22939&t=22940&t=22942&t=22946&t=22967&t=22968&t=22970&t=22972&t=22974&t=22977&t=22978&t=22979&t=22980&t=22981&t=23140&t=23141&t=23142&t=23144&t=23251&t=23402&t=23403&t=23404&t=23410&t=24046&t=25314&t=25315&t=25317&t=25334&t=25336&t=25337&t=25339&t=25340&t=25341&t=25342&t=25346&t=25347&t=27987&t=27989&t=27991&t=28002&t=28448&t=28450&t=28451&t=28453&t=28454&t=28455&t=28456&t=28458&t=28464&t=28466&t=30026&t=30029&t=30031&t=30032&t=30033&t=30034&t=30667&t=30668&t=30696&t=30698&t=30699&t=30702&e=2013-01-01&l=2021-12-31&s=19650

**Comment by jsayers-bsc** [comment]
Some more tags to flag. Mostly clapper rails at a PUMA colony.

tag_deploy_id | sensor_deploy_id
-- | --
18148 | 4789
12085 | 4789
12086 | 4789
12088 | 4789
12090 | 4789
12091 | 4789
12099 | 4789
12102 | 4789
12228 | 4789
13064 | 4789
13065 | 4789
13067 | 4789
13069 | 4789
13072 | 4789
16121 | 4789
16123 | 4789
16125 | 4789
16127 | 4789
16129 | 4789
16130 | 4789
16131 | 4789
16136 | 4789
16139 | 4789
16146 | 4789
16128 | 4789
16129 | 4789
16130 | 4789
16131 | 4789

**Comment by cjardine-bsc** [comment]
> 
> 
> Some more tags to flag. Mostly clapper rails at a PUMA colony in Manitoba
> tag_deploy_id 	sensor_deploy_id
> 18148 	4789
> 12085 	4789
> 12086 	4789
> 12088 	4789
> 12090 	4789
> 12091 	4789
> 12099 	4789
> 12102 	4789
> 12228 	4789
> 13064 	4789
> 13065 	4789
> 13067 	4789
> 13069 	4789
> 13072 	4789
> 16121 	4789
> 16123 	4789
> 16125 	4789
> 16127 	4789
> 16129 	4789
> 16130 	4789
> 16131 	4789
> 16136 	4789
> 16139 	4789
> 16146 	4789
> 16128 	4789
> 16129 	4789
> 16130 	4789
> 16131 	4789

Added. @jsayers-bsc If you have a moment can you look at the two previous notes from @leberrigan and @StuMackenzie? Those haven't been added yet.

**Comment by jsayers-bsc** [comment]
Block of time to flag: Everything on 2020-06-25 at receiver deployID 4237

https://motus.org/data/receiver/deployment/plot/?id=5237

**Comment by cjardine-bsc** [comment]
I can't really work with blocks of time currently. I'd need receiver deploy IDs and tag Deploy IDs.

**Comment by jsayers-bsc** [comment]
Sure you still want these posted to to the git issue? :)


tag_deploy_id | sensor_deploy_id | Comment
-- | -- | --
33566 | 7769 | EAME with same BI as CHSW at colony, showing up a day here, and a day   there
33571 | 7769 | EAME with same BI as CHSW at colony, showing up a day here, and a day   there
33358 | 7636 | Lewis's woodpecker in Pennsylvania; same BI as tags present
32925 | 7636 | Lewis's woodpecker in Pennsylvania; same BI as tags present
33546 | 7636 | Lewis's woodpecker in Pennsylvania; same BI as tags present
33550 | 7636 | Lewis's woodpecker in Pennsylvania; same BI as tags present
32928 | 7636 | Lewis's woodpecker in Pennsylvania; same BI as tags present
33558 | 7636 | Lewis's woodpecker in Pennsylvania; same BI as tags present
32128 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
32302 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
33129 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
33130 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
32572 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
32604 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
32605 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
33160 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
33164 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
33216 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
33239 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
32181 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
32183 | 7636 | GWWA/CERW; tags detected were known to be active in either Tennessee or   Maine at this time. Same BI as tags present
33478 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33479 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33480 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33481 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33482 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33483 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33484 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33485 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33486 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33487 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33488 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33489 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33490 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33491 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33492 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33493 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33495 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
33496 | 7338 | Shorebirds recently tagged on Hudson Bay showing up at in July at PUMA   colony with same BI
23403 | 5891 | RUBLS with detections in South America. Some of these may already be   flagged?
23410 | 5891 | RUBLS with detections in South America. Some of these may already be   flagged?
23141 | 5891 | RUBLS with detections in South America. Some of these may already be   flagged?
23142 | 5891 | RUBLS with detections in South America. Some of these may already be   flagged?
23140 | 5891 | RUBLS with detections in South America. Some of these may already be   flagged?
28456 | 7514 | RUBLS with detections in South America. Some of these may already be   flagged?
5512 | 3871 | RUBLS with detections in South America. Some of these may already be   flagged?
11080 | 3871 | RUBLS with detections in South America. Some of these may already be   flagged?
5515 | 3871 | RUBLS with detections in South America. Some of these may already be   flagged?
11069 | 4453 | RUBLS with detections in South America. Some of these may already be   flagged?
11081 | 4453 | RUBLS with detections in South America. Some of these may already be   flagged?
11263 | 4453 | RUBLS with detections in South America. Some of these may already be   flagged?
11074 | 4453 | RUBLS with detections in South America. Some of these may already be   flagged?
11071 | 4453 | RUBLS with detections in South America. Some of these may already be   flagged?
11082 | 4453 | RUBLS with detections in South America. Some of these may already be   flagged?
11073 | 4453 | RUBLS with detections in South America. Some of these may already be   flagged?
19039 | 5255 | RUBLS with detections in South America. Some of these may already be   flagged?
23402 | 5255 | RUBLS with detections in South America. Some of these may already be   flagged?
6473 | 4141 | RUBLS with detections in South America. Some of these may already be   flagged?
11078 | 4453 | RUBLS with detections in South America. Some of these may already be   flagged?
27989 | 3877 | RUBLS with detections in South America. Some of these may already be   flagged?
11080 | 3877 | RUBLS with detections in South America. Some of these may already be   flagged?
9864 | 3529 | RUBLS with detections in South America. Some of these may already be   flagged?
11072 | 3529 | RUBLS with detections in South America. Some of these may already be   flagged?
11067 | 3529 | RUBLS with detections in South America. Some of these may already be   flagged?
22968 | 7516 | RUBLS with detections in South America. Some of these may already be   flagged?
28451 | 7516 | RUBLS with detections in South America. Some of these may already be   flagged?
22934 | 7516 | RUBLS with detections in South America. Some of these may already be   flagged?
27989 | 7516 | RUBLS with detections in South America. Some of these may already be   flagged?
22933 | 7699 | RUBLS with detections in South America. Some of these may already be   flagged?
22930 | 7516 | RUBLS with detections in South America. Some of these may already be   flagged?
11075 | 3529 | RUBLS with detections in South America. Some of these may already be   flagged?
25317 | 7516 | RUBLS with detections in South America. Some of these may already be   flagged?
14233 | 3529 | RUBLS with detections in South America. Some of these may already be   flagged?
28464 | 7516 | RUBLS with detections in South America. Some of these may already be   flagged?
22933 | 7516 | RUBLS with detections in South America. Some of these may already be   flagged?
6475 | 3529 | RUBLS with detections in South America. Some of these may already be   flagged?
30034 | 7516 | RUBLS with detections in South America. Some of these may already be   flagged?
22940 | 7516 | RUBLS with detections in South America. Some of these may already be   flagged?
30026 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
28450 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
22933 | 7664 | RUBLS with detections in South America. Some of these may already be   flagged?
30033 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
28454 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
22940 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
22929 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
22940 | 7664 | RUBLS with detections in South America. Some of these may already be   flagged?
22968 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
22934 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
27989 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
28455 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
22930 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
30034 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
22934 | 7664 | RUBLS with detections in South America. Some of these may already be   flagged?
22968 | 7664 | RUBLS with detections in South America. Some of these may already be   flagged?
22933 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
22930 | 7664 | RUBLS with detections in South America. Some of these may already be   flagged?
22977 | 7515 | RUBLS with detections in South America. Some of these may already be   flagged?
6479 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
9847 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
9839 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
6472 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
6002 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
9861 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
9857 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
9838 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
6010 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
6475 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
5997 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
9841 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
9859 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
11080 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
9836 | 3713 | RUBLS with detections in South America. Some of these may already be   flagged?
27989 | 3872 | RUBLS with detections in South America. Some of these may already be   flagged?
14220 | 5065 | RUBLS with detections in South America. Some of these may already be   flagged?
22930 | 3872 | RUBLS with detections in South America. Some of these may already be   flagged?
23410 | 3872 | RUBLS with detections in South America. Some of these may already be   flagged?
6475 | 3696 | RUBLS with detections in South America. Some of these may already be   flagged?
22933 | 3872 | RUBLS with detections in South America. Some of these may already be   flagged?
11083 | 3872 | RUBLS with detections in South America. Some of these may already be   flagged?
19036 | 5022 | RUBLS with detections in South America. Some of these may already be   flagged?
25317 | 7517 | RUBLS with detections in South America. Some of these may already be   flagged?
22930 | 7517 | RUBLS with detections in South America. Some of these may already be   flagged?
27989 | 7517 | RUBLS with detections in South America. Some of these may already be   flagged?
18662 | 5022 | RUBLS with detections in South America. Some of these may already be   flagged?
28464 | 7517 | RUBLS with detections in South America. Some of these may already be   flagged?
5998 | 4152 | RUBLS with detections in South America. Some of these may already be   flagged?
5999 | 4152 | RUBLS with detections in South America. Some of these may already be   flagged?
22933 | 7517 | RUBLS with detections in South America. Some of these may already be   flagged?
9859 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
22930 | 7742 | RUBLS with detections in South America. Some of these may already be   flagged?
9835 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
9861 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
5997 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
9858 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
11068 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
11079 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
22933 | 7742 | RUBLS with detections in South America. Some of these may already be   flagged?
9841 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
11074 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
11072 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
9838 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
14223 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
11069 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
6472 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
9848 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
9836 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
22940 | 7742 | RUBLS with detections in South America. Some of these may already be   flagged?
22968 | 7742 | RUBLS with detections in South America. Some of these may already be   flagged?
6010 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
9855 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
9843 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
11080 | 3027 | RUBLS with detections in South America. Some of these may already be   flagged?
11080 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
9838 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
11262 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
6479 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
9861 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
9836 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
9864 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
6002 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
9859 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
9847 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
5997 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
6010 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
9843 | 3869 | RUBLS with detections in South America. Some of these may already be   flagged?
11080 | 2952 | RUBLS with detections in South America. Some of these may already be   flagged?
9838 | 2952 | RUBLS with detections in South America. Some of these may already be   flagged?
5997 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
6474 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
11078 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9847 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
6470 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9846 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
6479 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
11080 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9843 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9859 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9839 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
11075 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9841 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9838 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
6010 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
6002 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9836 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9861 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9849 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
6472 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
9855 | 3857 | RUBLS with detections in South America. Some of these may already be   flagged?
30034 | 7701 | RUBLS with detections in South America. Some of these may already be   flagged?
22940 | 7701 | RUBLS with detections in South America. Some of these may already be   flagged?
5515 | 3192 | RUBLS with detections in South America. Some of these may already be   flagged?
22968 | 7701 | RUBLS with detections in South America. Some of these may already be   flagged?
22930 | 7701 | RUBLS with detections in South America. Some of these may already be   flagged?
5513 | 3192 | RUBLS with detections in South America. Some of these may already be   flagged?
5514 | 3192 | RUBLS with detections in South America. Some of these may already be   flagged?
22933 | 7701 | RUBLS with detections in South America. Some of these may already be   flagged?
5512 | 3192 | RUBLS with detections in South America. Some of these may already be   flagged?
5511 | 3192 | RUBLS with detections in South America. Some of these may already be   flagged?
9863 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
9836 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
9838 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
6471 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
6012 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
6482 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
6477 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
6008 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
6475 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
9835 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
6481 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
11084 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
9841 | 3526 | RUBLS with detections in South America. Some of these may already be   flagged?
22930 | 7700 | RUBLS with detections in South America. Some of these may already be   flagged?
22968 | 7700 | RUBLS with detections in South America. Some of these may already be   flagged?
6474 | 2951 | RUBLS with detections in South America. Some of these may already be   flagged?
22940 | 7700 | RUBLS with detections in South America. Some of these may already be   flagged?
6010 | 3028 | RUBLS with detections in South America. Some of these may already be   flagged?
5997 | 2951 | RUBLS with detections in South America. Some of these may already be   flagged?
6002 | 2951 | RUBLS with detections in South America. Some of these may already be   flagged?
5991 | 2951 | RUBLS with detections in South America. Some of these may already be   flagged?
6479 | 2951 | RUBLS with detections in South America. Some of these may already be   flagged?
6010 | 2951 | RUBLS with detections in South America. Some of these may already be   flagged?
22933 | 7700 | RUBLS with detections in South America. Some of these may already be   flagged?
5997 | 3028 | RUBLS with detections in South America. Some of these may already be   flagged?

**Comment by cjardine-bsc** [comment]
Done. 

How are the duplicate entries happening though? Shouldn't these already be flagged as filtered?

**Comment by jsayers-bsc** [comment]
> How are the duplicate entries happening though? Shouldn't these already be flagged as filtered?

I was just searching for deployIDs so if they were flagged they'd still show up in the list. I only noticed when I tried to click through for more information and saw that they were already absent.

**Comment by jsayers-bsc** [comment]
tag_deploy_id | sensor_deploy_id | comment
-- | -- | --
33731 | 7338 | Bird that is presumed dead in the vicinity of a receiver and they'd like   it hidden

**Comment by cjardine-bsc** [comment]
I don't think we want to use the filter option to get rid of these. I'd prefer if we set an end date on the tag deployment and mark the tag as deprecated.

**Comment by jsayers-bsc** [comment]
> I don't think we want to use the filter option to get rid of these. I'd prefer if we set an end date on the tag deployment and mark the tag as deprecated.

Yes that's definitely better. Scratch that then.

**Comment by jsayers-bsc** [comment]
tag_deploy_id | sensor_deploy_id | comment
-- | -- | --
17653 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
18809 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
22638 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
22934 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
22962 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
23829 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
24662 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
24887 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
24888 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
24891 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
25001 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
25975 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
27582 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
27590 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
27594 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
27596 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
28051 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
28152 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
28193 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
28207 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
28692 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
28891 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
28999 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
29700 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
29702 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
29707 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
29913 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
30653 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
30927 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
31121 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
31164 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
31170 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
31731 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
32017 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
32112 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
32607 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
32739 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
32833 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
32875 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
33015 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
33114 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
33117 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
33148 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
33372 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
33411 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
33542 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
33990 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
33993 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
34040 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
34405 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
34406 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
34491 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
34531 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
35436 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor
35449 | 7742 | Every detction in daily summary presumed by station manager to be false   positive due to noise or other unknown factor

**Comment by cjardine-bsc** [comment]
Do we want the whole deployment filtered then?

**Comment by jsayers-bsc** [comment]
> 
> 
> Do we want the whole deployment filtered then?
yes

**Comment by cjardine-bsc** [comment]
Okay. Should be able to just add it without the tag_deploy_ids 

NULL	7742	NULL	NULL	NULL	NULL	NULL	Every detction in daily summary presumed by station manager to be false positive due to noise or other unknown factor

**Comment by jsayers-bsc** [comment]
> 
> 
> Okay. Should be able to just add it without the tag_deploy_ids
> 
> NULL 7742 NULL NULL NULL NULL NULL Every detction in daily summary presumed by station manager to be false positive due to noise or other unknown factor

So just filter out everything based on sensor_deploy_id?

**Comment by cjardine-bsc** [comment]
Yes.

**Comment by jsayers-bsc** [comment]
Re stations that might be best filtered out entirely (especially the first 2). The third may be better suited by a Project whitelist.

Tadoussac Andre https://motus.org/data/receiver/deployment/plot/?id=3454
Drasher https://motus.org/data/receiver/deployment/plot/?id=7521
Agrosvia Blackpoll https://motus.org/data/receiver/deployment/plot/?id=7516

**Comment by cjardine-bsc** [comment]
The word "might" is in there....

Do you want to discuss with Stu et al? Or should I filter?
